config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :articles

  resources :player_game_statistics

  get 'search/index'

  get 'home/index'

  resources :player_goals

  resources :team_tournaments

  resources :player_team_tournaments

  resources :players

  resources :games

  resources :teams

  post 'team_list' => "teams#team_list", as: :team_list
  resources :players do
    resources :user_profiles
  end
  resources :leagues do
    resources :tournaments
    get 'tournaments/:id/add_team' => 'tournaments#add_team'
    get 'tournaments/:id/games' => 'tournaments#games'
  end
  get 'games/:id/stats' => 'games#stats'

  root 'home#index'

end

app/models/team_tournament.rb
class TeamTournament < ActiveRecord::Base
	belongs_to :team
	belongs_to :tournament
end

app/controllers/team_tournaments_controller.rb
class TeamTournamentsController < ApplicationController
  before_action :set_team_tournament, only: [:show, :edit, :update, :destroy]
  before_action :authenticate, except: [:index, :show]
  # GET /team_tournaments
  # GET /team_tournaments.json
  def index
    @team_tournaments = TeamTournament.all
  end

  # GET /team_tournaments/1
  # GET /team_tournaments/1.json
  def show
  end

  # GET /team_tournaments/new
  def new
    @team_tournament = TeamTournament.new
  end

  # GET /team_tournaments/1/edit
  def edit
  end

  # POST /team_tournaments
  # POST /team_tournaments.json
  def create
    @team_tournament = TeamTournament.new(team_tournament_params)

    respond_to do |format|
      if @team_tournament.save
        format.html { redirect_to @team_tournament, notice: 'Team tournament was successfully created.' }
        format.json { render :show, status: :created, location: @team_tournament }
      else
        format.html { render :new }
        format.json { render json: @team_tournament.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /team_tournaments/1
  # PATCH/PUT /team_tournaments/1.json
  def update
    respond_to do |format|
      if @team_tournament.update(team_tournament_params)
        format.html { redirect_to @team_tournament, notice: 'Team tournament was successfully updated.' }
        format.json { render :show, status: :ok, location: @team_tournament }
      else
        format.html { render :edit }
        format.json { render json: @team_tournament.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /team_tournaments/1
  # DELETE /team_tournaments/1.json
  def destroy
    @team_tournament.destroy
    respond_to do |format|
      format.html { redirect_to team_tournaments_url, notice: 'Team tournament was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team_tournament
      @team_tournament = TeamTournament.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def team_tournament_params
      params.require(:team_tournament).permit(:team_id, :tournament_id)
    end
end

app/helpers/team_tournaments_helper.rb
module TeamTournamentsHelper
end

app/views/team_tournaments/_form.html.erb
<%= form_for(@team_tournament) do |f| %>
  <% if @team_tournament.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@team_tournament.errors.count, "error") %> prohibited this team_tournament from being saved:</h2>

      <ul>
      <% @team_tournament.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :team_id %><br>
    <%= f.number_field :team_id %>
  </div>
  <div class="field">
    <%= f.label :tournament_id %><br>
    <%= f.number_field :tournament_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/team_tournaments/edit.html.erb
<h1>Editing team_tournament</h1>

<%= render 'form' %>

<%= link_to 'Show', @team_tournament %> |
<%= link_to 'Back', team_tournaments_path %>

app/views/team_tournaments/index.html.erb
<h1>Listing team_tournaments</h1>

<table>
  <thead>
    <tr>
      <th>Team</th>
      <th>Tournament</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @team_tournaments.each do |team_tournament| %>
      <tr>
        <td><%= team_tournament.team_id %></td>
        <td><%= team_tournament.tournament_id %></td>
        <td><%= link_to 'Show', team_tournament %></td>
        <td><%= link_to 'Edit', edit_team_tournament_path(team_tournament) %></td>
        <td><%= link_to 'Destroy', team_tournament, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Team tournament', new_team_tournament_path %>

app/views/team_tournaments/new.html.erb
<h1>New team_tournament</h1>

<%= render 'form' %>

<%= link_to 'Back', team_tournaments_path %>

app/views/team_tournaments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Team:</strong>
  <%= @team_tournament.team_id %>
</p>

<p>
  <strong>Tournament:</strong>
  <%= @team_tournament.tournament_id %>
</p>

<%= link_to 'Edit', edit_team_tournament_path(@team_tournament) %> |
<%= link_to 'Back', team_tournaments_path %>