config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :articles

  resources :player_game_statistics

  get 'search/index'

  get 'home/index'

  resources :player_goals

  resources :team_tournaments

  resources :player_team_tournaments

  resources :players

  resources :games

  resources :teams

  post 'team_list' => "teams#team_list", as: :team_list
  resources :players do
    resources :user_profiles
  end
  resources :leagues do
    resources :tournaments
    get 'tournaments/:id/add_team' => 'tournaments#add_team'
    get 'tournaments/:id/games' => 'tournaments#games'
  end
  get 'games/:id/stats' => 'games#stats'

  root 'home#index'

end

app/models/tournament.rb
class Tournament < ActiveRecord::Base
	has_many :team_tournaments, dependent: :destroy
	has_many :teams, :through => :team_tournaments
	has_many :games
	belongs_to :league
	has_many :player_goals, dependent: :destroy
	has_many :players, :through => :player_team_tournaments

    def self.get_current_tournaments
        self.where("year = ? AND semester =?",self.current_tournament[:year],self.current_tournament[:semester])
    end
    def self.current_tournament
        year=Date.current.year
        semester=(Date.current.month>6)? 2 : 1
        current_tournament={:semester => semester,:year => year}
        return current_tournament
    end
end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController
  before_action :set_tournament, only: [:show, :edit, :update, :destroy, :games]
  before_action :authenticate, except: [:index, :show]

  # GET /tournaments
  # GET /tournaments.json
  def index
    league=League.find(params[:league_id])
    @tournaments = league.tournaments
  end

  # GET /tournaments/1
  # GET /tournaments/1.json
  def show
    @teams=@tournament.teams
    @teams = @teams.sort { |a,b| a.score(@tournament)[:goal_difference] <=> b.score(@tournament)[:goal_difference] }
    @teams = @teams.sort { |a,b| a.score(@tournament)[:points] <=> b.score(@tournament)[:points] }
    @teams.reverse!
    @games = @tournament.games
  end

  # GET /tournaments/new
  def new
    league=League.find(params[:league_id])
    @tournament = league.tournaments.build
  end

  # GET /tournaments/1/edit
  def edit
  end

  def add_team
    @tournament=Tournament.find(params[:id])
    @team_tournament=@tournament.team_tournaments.build
  end

  def games
    @games = @tournament.games
  end

  # POST /tournaments
  # POST /tournaments.json
  def create
    league=League.find(params[:league_id])
    @tournament = league.tournaments.create(tournament_params)

    respond_to do |format|
      if @tournament.save
        format.html { redirect_to [@tournament.league,@tournam], notice: 'Tournament was successfully created.' }
        format.json { render :show, status: :created, location: @tournament }
      else
        format.html { render :new }
        format.json { render json: @tournament.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tournaments/1
  # PATCH/PUT /tournaments/1.json
  def update
    respond_to do |format|
      if @tournament.update(tournament_params)
        format.html { redirect_to @tournament, notice: 'Tournament was successfully updated.' }
        format.json { render :show, status: :ok, location: @tournament }
      else
        format.html { render :edit }
        format.json { render json: @tournament.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tournaments/1
  # DELETE /tournaments/1.json
  def destroy
    @tournament.destroy
    respond_to do |format|
      format.html { redirect_to tournaments_url, notice: 'Tournament was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tournament
      @tournament = Tournament.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tournament_params
      params.require(:tournament).permit(:year, :semester, :league_id)
    end
end

app/helpers/tournaments_helper.rb
module TournamentsHelper
end

app/views/tournaments/_form.html.erb
<%= form_for([@tournament.league,@tournament]) do |f| %>
  <% if @tournament.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tournament.errors.count, "error") %> prohibited this tournament from being saved:</h2>

      <ul>
      <% @tournament.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :semester %><br>
    <%= f.number_field :semester %>
  </div>
  <div class="field">
    <%= f.label :league_id %><br>
    <%= f.number_field :league_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tournaments/add_team.html.erb
<%= form_for(@team_tournament) do |f| %>
  <% if @team_tournament.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@team_tournament.errors.count, "error") %> prohibited this team_tournament from being saved:</h2>

      <ul>
      <% @team_tournament.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :team_id %><br>
    <%= f.number_field :team_id %>
  </div>
  <div class="field">
    <%= f.label :tournament_id %><br>
    <%= f.number_field :tournament_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tournaments/edit.html.erb
<h1>Editing tournament</h1>

<%= render 'form' %>

<%= link_to 'Show', @tournament %> |
<%= link_to 'Back', tournaments_path %>

app/views/tournaments/games.html.erb
<h1>Listing games</h1>
<div class="bs-example">
    <ul class="nav nav-tabs">

      <% for i in 1..12 %>
        <li><a data-toggle="tab" href=<%="#Fecha"+i.to_s%>><%="Fecha "+i.to_s%></a></li>
      <% end %>
      </ul>
        <div class="tab-content">
      <% for i in  1..12%>
        <div id= <%="Fecha"+i.to_s%> class="tab-pane fade">
            <table class="table table-bordered">
  <thead>
    <tr>
      <th>Team</th>
      <th>Opponent</th>
      <th>Team score</th>
      <th>Opponent score</th>
      <th>Date</th>
      <th>Location</th>      
      <th>Liga</th>
      <th>fecha</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <% if game.fecha==i %>
        
        <tr>
          <td><%= link_to game.team.name, team_path(game.team.id) %></td>
          <td><%= link_to game.opponent.name, team_path(game.opponent.id) %></td>
          <td><%= game.team_score %></td>
          <td><%= game.opponent_score %></td>
          <td><%= game.date %></td>
          <td><%= game.location %></td>
          <td><%= game.tournament.league.name %></td>
          <td><%= game.fecha %></td>
          <td><%= link_to 'Show', game %></td>
          <td><%= link_to 'Edit', edit_game_path(game) %></td>
          <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
        </div>
      <% end %>       
      </div>

app/views/tournaments/index.html.erb
<h1>Listing tournaments</h1>

<table>
  <thead>
    <tr>
      <th>Year</th>
      <th>Semester</th>
      <th>League</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tournaments.each do |tournament| %>
      <tr>
        <td><%= tournament.year %></td>
        <td><%= tournament.semester %></td>
        <td><%= League.find(tournament.league_id).name %></td>
        <td><%= link_to 'Show', [tournament.league, tournament] %></td>
        <td><%= link_to 'Edit', edit_league_tournament_path(tournament.league, tournament) %></td>
        <td><%= link_to 'Destroy', [tournament.league,tournament], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tournament', new_league_tournament_path %>

app/views/tournaments/new.html.erb
<h1>New tournament</h1>

<%= render 'form' %>

<%= link_to 'Back', league_tournaments_path %>

app/views/tournaments/show.html.erb
<p id="notice"><%= notice %></p>

<h1 class="h1"><%= League.find(@tournament.league_id).name %></h1>

<h2 class="h2">Tabla de posiciones del torneo <%= @tournament.semester==1? 'apertura' : 'clausura'  %> del año <%= @tournament.year %></h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Partidos Jugados</th>
      <th>Goles a Favor</th>
      <th>Goles en Contra</th>
      <th>Diferencia de goles</th>
      <th>Puntos</th>
    </tr>
  </thead>

  <tbody>
    <% @teams.each do |team| %>
      <tr>
        <td><img src=<%=team.logo_link  %> border="0" style="height:50px; width:50px;" /><%= link_to team.name, team_path(team.id) %></td>
        <td><%= team.score(@tournament)[:games_played]%></td>
        <td><%= team.score(@tournament)[:goals_favor]%></td>
        <td><%= team.score(@tournament)[:goals_against]%></td>
        <td><%= team.score(@tournament)[:goal_difference]%></td>
        <td><%= team.score(@tournament)[:points]%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<h1>Partidos</h1>
<div class="bs-example">
    <ul class="nav nav-tabs">
    <li class="active"><a data-toggle="tab" href="#AllGames">Todos</a></li>
    <li>
      <div class="dropdown">
        <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
          <% for i in 1..12 %>
        <li><a data-toggle="tab" href=<%="#Fecha"+i.to_s%>><%="Fecha "+i.to_s%></a></li>
      <% end %>
        </ul>
      </div>
      </li>
      <% for i in 1..12 %>
        <li><a data-toggle="tab" href=<%="#Fecha"+i.to_s%>><%="Fecha "+i.to_s%></a></li>
      <% end %>
      </ul>
        <div class="tab-content">
        <div id= "AllGames" class="tab-pane fade active in">
            <table class="table table-bordered">
  <thead>
    <tr>
      <th>Team</th>
      <th>Opponent</th>
      <th>Team score</th>
      <th>Opponent score</th>
      <th>Date</th>
      <th>Location</th>      
      <th>Liga</th>
      <th>fecha</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>    
        <tr>
        <td><img src=<%=game.team.logo_link  %> border="0" style="height:50px; width:50px;" /></a><%= link_to game.team.name, team_path(game.team.id) %></td>
        <td><img src=<%=game.opponent.logo_link  %> border="0" style="height:50px; width:50px;" /><%= link_to game.opponent.name, team_path(game.opponent.id) %></td>
          <td><%= game.team_score %></td>
          <td><%= game.opponent_score %></td>
          <td><%= game.date %></td>
          <td><%= game.location %></td>
          <td><%= game.tournament.league.name %></td>
          <td><%= game.fecha %></td>
          <td><%= link_to 'Show', game %></td>
          <td><%= link_to 'Edit', edit_game_path(game) %></td>
          <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
  </tbody>
</table>
        </div>



<% for i in  1..12%>
  <div id= <%="Fecha"+i.to_s%> class="tab-pane fade">
      <table class="table table-bordered">
  <thead>
    <tr>
      <th>Team</th>
      <th>Opponent</th>
      <th>Team score</th>
      <th>Opponent score</th>
      <th>Date</th>
      <th>Location</th>      
      <th>Liga</th>
      <th>fecha</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <% if game.fecha==i %>
        
        <tr>
        <td><img src=<%=game.team.logo_link  %> border="0" style="height:50px; width:50px;" /></a><%= link_to game.team.name, team_path(game.team.id) %></td>
        <td><img src=<%=game.opponent.logo_link  %> border="0" style="height:50px; width:50px;" /><%= link_to game.opponent.name, team_path(game.opponent.id) %></td>
          <td><%= game.team_score %></td>
          <td><%= game.opponent_score %></td>
          <td><%= game.date %></td>
          <td><%= game.location %></td>
          <td><%= game.tournament.league.name %></td>
          <td><%= game.fecha %></td>
          <td><%= link_to 'Show', game %></td>
          <td><%= link_to 'Edit', edit_game_path(game) %></td>
          <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
        </div>
      <% end %>       
      </div>