config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :articles

  resources :player_game_statistics

  get 'search/index'

  get 'home/index'

  resources :player_goals

  resources :team_tournaments

  resources :player_team_tournaments

  resources :players

  resources :games

  resources :teams

  post 'team_list' => "teams#team_list", as: :team_list
  resources :players do
    resources :user_profiles
  end
  resources :leagues do
    resources :tournaments
    get 'tournaments/:id/add_team' => 'tournaments#add_team'
    get 'tournaments/:id/games' => 'tournaments#games'
  end
  get 'games/:id/stats' => 'games#stats'

  root 'home#index'

end

app/models/game.rb
class Game < ActiveRecord::Base
	belongs_to :team
	belongs_to :tournament
	belongs_to :opponent, :class_name => "Team"
	has_many :player_game_statistics
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy, :stats]
  before_action :authenticate, except: [:index]
  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @teams = Team.all
    @game = Game.new
  end

  def stats
    @team_stats = []
    @opponent_stats = []
    for player in @team_players
      stat=PlayerGameStatistic.find_by game_id: @game.id, player_id: player.id
      if(!stat)
        stat=PlayerGameStatistic.new({:game_id => @game.id,:player_id=>player.id})
      end
      print "Found this stat ",stat.player_id, stat.goals
      @team_stats.push(stat)
    end
    for player in @opponent_players
      stat=PlayerGameStatistic.find_by game_id: @game.id, player_id: player.id
      if !stat
        stat = PlayerGameStatistic.new({:game_id => @game.id,:player_id=>player.id})
      end
      @opponent_stats.push(stat)
    end
  end
  # GET /games/1/edit
  def edit
    print "ID:", @game.tournament_id
    @tournament = Tournament.find(@game.tournament_id)
    @teams = @tournament.teams
    @league = League.find(@tournament.league_id)
    print "LEAGUE", @league
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: game_params }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
      get_team_players
      @player_game_statistic=PlayerGameStatistic.new({:game_id => @game.id,:player_id=>Player.all.first.id})
      get_opponent_players
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:team_id, :opponent_id, :team_score, :opponent_score, :date, :location,:tournament_id, :fecha)
    end

    def get_team_players
      @team_players=@game.team.get_current_players
    end

    def get_opponent_players
      @opponent_players=@game.opponent.get_current_players  
    end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
  <%= collection_select(:league, :id, League.all, :id, :name,:prompt => "Elija liga") %>
  </div> 
  <div class="field"> 
  <%= f.select :team_id, options_from_collection_for_select(@teams, "id", "name", @game.team_id) %> 
  </div>  
  <div class="field"> 
  <%= f.select :opponent_id, options_from_collection_for_select(@teams, "id", "name", @game.opponent_id) %> 
  </div>
  <div class="field">
    <%= f.label :team_score %><br>
    <%= f.number_field :team_score %>
  </div>
  <div class="field">
    <%= f.label :opponent_score %><br>
    <%= f.number_field :opponent_score %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :tournament_id %><br>
    <%= f.number_field :tournament_id %>
  </div>
  <div class="field">
    <%= f.label :fecha %><br>
    <%= f.number_field :fecha %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<h1>Partidos</h1>
<div class="bs-example">
    <ul class="nav nav-tabs">
    <li class="active"><a data-toggle="tab" href="#AllGames">Todos</a></li>
    <li>
      <div class="dropdown">
        <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
          <% for i in 1..12 %>
        <li><a data-toggle="tab" href=<%="#Fecha"+i.to_s%>><%="Fecha "+i.to_s%></a></li>
      <% end %>
        </ul>
      </div>
      </li>
      <% for i in 1..12 %>
        <li><a data-toggle="tab" href=<%="#Fecha"+i.to_s%>><%="Fecha "+i.to_s%></a></li>
      <% end %>
      </ul>
        <div class="tab-content">
        <div id= "AllGames" class="tab-pane fade active in">
            <table class="table table-bordered">
  <thead>
    <tr>
      <th>Team</th>
      <th>Opponent</th>
      <th>Team score</th>
      <th>Opponent score</th>
      <th>Date</th>
      <th>Location</th>      
      <th>Liga</th>
      <th>fecha</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>    
        <tr>
        <td><img src=<%=game.team.logo_link  %> border="0" style="height:50px; width:50px;" /></a><%= link_to game.team.name, team_path(game.team.id) %></td>
        <td><img src=<%=game.opponent.logo_link  %> border="0" style="height:50px; width:50px;" /><%= link_to game.opponent.name, team_path(game.opponent.id) %></td>
          <td><%= game.team_score %></td>
          <td><%= game.opponent_score %></td>
          <td><%= game.date %></td>
          <td><%= game.location %></td>
          <td><%= game.tournament.league.name %></td>
          <td><%= game.fecha %></td>
          <td><%= link_to 'Show', game %></td>
          <td><%= link_to 'Edit', edit_game_path(game) %></td>
          <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
  </tbody>
</table>
        </div>



<% for i in  1..12%>
  <div id= <%="Fecha"+i.to_s%> class="tab-pane fade">
      <table class="table table-bordered">
  <thead>
    <tr>
      <th>Team</th>
      <th>Opponent</th>
      <th>Team score</th>
      <th>Opponent score</th>
      <th>Date</th>
      <th>Location</th>      
      <th>Liga</th>
      <th>fecha</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <% if game.fecha==i %>
        
        <tr>
        <td><img src=<%=game.team.logo_link  %> border="0" style="height:50px; width:50px;" /></a><%= link_to game.team.name, team_path(game.team.id) %></td>
        <td><img src=<%=game.opponent.logo_link  %> border="0" style="height:50px; width:50px;" /><%= link_to game.opponent.name, team_path(game.opponent.id) %></td>
          <td><%= game.team_score %></td>
          <td><%= game.opponent_score %></td>
          <td><%= game.date %></td>
          <td><%= game.location %></td>
          <td><%= game.tournament.league.name %></td>
          <td><%= game.fecha %></td>
          <td><%= link_to 'Show', game %></td>
          <td><%= link_to 'Edit', edit_game_path(game) %></td>
          <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
        </div>
      <% end %>       
      </div>
<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<h1>New game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Team:</strong>
  <%= @game.team.name %>
</p>

<p>
  <strong>Opponent:</strong>
  <%= @game.opponent.name %>
</p>

<p>
  <strong>Team score:</strong>
  <%= @game.team_score %>
</p>

<p>
  <strong>Opponent score:</strong>
  <%= @game.opponent_score %>
</p>

<p>
  <strong>Date:</strong>
  <%= @game.date %>
</p>

<p>
  <strong>Location:</strong>
  <%= @game.location %>
</p>


<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>

app/views/games/stats.html.erb
  <div class="container">
	  <div class="row">
		  <div class="col-lg-6">
			  <div class="container">
			    <div class="row">
			    	<div class="col-lg-1">
			    	<strong><%= @game.team.name %></strong>
			    	</div>
			    	<div class="col-lg-1"><%= @game.team_score  %></div>
			    </div>
			    <div class="row">
			    <div class="field col-lg-1">
			        Player
			      </div>
			      <div class="field col-lg-1">
			        Goals
			      </div>
			      <div class="field col-lg-1">
			        Yellow Cards
			      </div>
			      <div class="field col-lg-1">
			      	Dos Minutos
			      </div>
			      <div class="field col-lg-1">
			        Red Cards
			      </div>
			    </div>
			    <% @team_stats.each do |stat| %>
			    <div class="row">
			      <div class="field col-lg-1">
			        <%= stat.player.name %>
			      </div>
			  		<%= render 'player_game_statistics/form', :stat=>stat %>
			    </div>
			    <% end %>
			  </div>
		  </div>
		  	<div class="col-lg-6">
			    <div class="container">
				<div class="row">
			    	<div class="col-lg-1">
			    	<strong><%= @game.opponent.name %></strong>
			    	</div>
			    	<div class="col-lg-1"><%= @game.opponent_score  %></div>
			    </div>
			    <div class="row">
			    <div class="field col-lg-1">
			        Player
			      </div>
			      <div class="field col-lg-1">
			        Goals
			      </div>
			      <div class="field col-lg-1">
			        Yellow Cards
			      </div>
			      <div class="field col-lg-1">
			        Dos minutos
			      </div>
			      <div class="field col-lg-1">
			        Red Cards
			      </div>
			    </div>
			    <% @opponent_stats.each do |stat| %>
			    <div class="row">
			      <div class="field col-lg-1">
			        <%= stat.player.name %>
			        goles<%= stat.goals %>
			      </div>
			  		<%= render 'player_game_statistics/form', :stat=>stat %>
			    </div>
			    <% end %>
			  </div>
		  </div>
	  </div>
  </div>
  <button class="btn btn-default btn-success" id="submitForms">Submit</button>