config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :articles

  resources :player_game_statistics

  get 'search/index'

  get 'home/index'

  resources :player_goals

  resources :team_tournaments

  resources :player_team_tournaments

  resources :players

  resources :games

  resources :teams

  post 'team_list' => "teams#team_list", as: :team_list
  resources :players do
    resources :user_profiles
  end
  resources :leagues do
    resources :tournaments
    get 'tournaments/:id/add_team' => 'tournaments#add_team'
    get 'tournaments/:id/games' => 'tournaments#games'
  end
  get 'games/:id/stats' => 'games#stats'

  root 'home#index'

end

app/models/player_goal.rb
class PlayerGoal < ActiveRecord::Base
	belongs_to :player
	belongs_to :tournament
end

app/controllers/player_goals_controller.rb
class PlayerGoalsController < ApplicationController
  before_action :set_player_goal, only: [:show, :edit, :update, :destroy]
  before_action :authenticate, except: [:index, :show]
  # GET /player_goals
  # GET /player_goals.json
  def index
    @player_goals = PlayerGoal.all
  end

  # GET /player_goals/1
  # GET /player_goals/1.json
  def show
  end

  # GET /player_goals/new
  def new
    @player_goal = PlayerGoal.new
  end

  # GET /player_goals/1/edit
  def edit
  end

  # POST /player_goals
  # POST /player_goals.json
  def create
    @player_goal = PlayerGoal.new(player_goal_params)

    respond_to do |format|
      if @player_goal.save
        format.html { redirect_to @player_goal, notice: 'Player goal was successfully created.' }
        format.json { render :show, status: :created, location: @player_goal }
      else
        format.html { render :new }
        format.json { render json: @player_goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /player_goals/1
  # PATCH/PUT /player_goals/1.json
  def update
    respond_to do |format|
      if @player_goal.update(player_goal_params)
        format.html { redirect_to @player_goal, notice: 'Player goal was successfully updated.' }
        format.json { render :show, status: :ok, location: @player_goal }
      else
        format.html { render :edit }
        format.json { render json: @player_goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /player_goals/1
  # DELETE /player_goals/1.json
  def destroy
    @player_goal.destroy
    respond_to do |format|
      format.html { redirect_to player_goals_url, notice: 'Player goal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player_goal
      @player_goal = PlayerGoal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_goal_params
      params.require(:player_goal).permit(:player_id, :tournament_id, :goals)
    end
end

app/helpers/player_goals_helper.rb
module PlayerGoalsHelper
end

app/views/player_goals/_form.html.erb
<%= form_for(@player_goal) do |f| %>
  <% if @player_goal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@player_goal.errors.count, "error") %> prohibited this player_goal from being saved:</h2>

      <ul>
      <% @player_goal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :player_id %><br>
    <%= f.number_field :player_id %>
  </div>
  <div class="field">
    <%= f.label :tournament_id %><br>
    <%= f.number_field :tournament_id %>
  </div>
  <div class="field">
    <%= f.label :goals %><br>
    <%= f.number_field :goals %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/player_goals/edit.html.erb
<h1>Editing player_goal</h1>

<%= render 'form' %>

<%= link_to 'Show', @player_goal %> |
<%= link_to 'Back', player_goals_path %>

app/views/player_goals/index.html.erb
<h1>Listing player_goals</h1>

<table>
  <thead>
    <tr>
      <th>Player</th>
      <th>Tournament</th>
      <th>Goals</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @player_goals.each do |player_goal| %>
      <tr>
        <td><%= player_goal.player_id %></td>
        <td><%= player_goal.tournament_id %></td>
        <td><%= player_goal.goals %></td>
        <td><%= link_to 'Show', player_goal %></td>
        <td><%= link_to 'Edit', edit_player_goal_path(player_goal) %></td>
        <td><%= link_to 'Destroy', player_goal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Player goal', new_player_goal_path %>

app/views/player_goals/new.html.erb
<h1>New player_goal</h1>

<%= render 'form' %>

<%= link_to 'Back', player_goals_path %>

app/views/player_goals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Player:</strong>
  <%= @player_goal.player_id %>
</p>

<p>
  <strong>Tournament:</strong>
  <%= @player_goal.tournament_id %>
</p>

<p>
  <strong>Goals:</strong>
  <%= @player_goal.goals %>
</p>

<%= link_to 'Edit', edit_player_goal_path(@player_goal) %> |
<%= link_to 'Back', player_goals_path %>